# Generated by Django 5.0.2 on 2024-02-26 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_to_answer',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='image_after',
            field=models.FileField(blank=True, default='', null=True, upload_to='media_after_question/image/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'jpeg200', 'gif', 'tiff', 'bmp', 'webp', 'psd', 'heif', 'svg', 'pdf', 'eps', 'ai', 'cdr', 'wmf', 'eme'))]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_before',
            field=models.FileField(blank=True, default='', null=True, upload_to='media_before_question/image/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'jpeg200', 'gif', 'tiff', 'bmp', 'webp', 'psd', 'heif', 'svg', 'pdf', 'eps', 'ai', 'cdr', 'wmf', 'eme'))]),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_after',
            field=models.FileField(blank=True, default='', null=True, upload_to='media_after_question/video', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'jpeg200', 'gif', 'tiff', 'bmp', 'webp', 'psd', 'heif', 'svg', 'pdf', 'eps', 'ai', 'cdr', 'wmf', 'eme'))]),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_before',
            field=models.FileField(blank=True, default='', null=True, upload_to='media_before_question/video', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'jpeg200', 'gif', 'tiff', 'bmp', 'webp', 'psd', 'heif', 'svg', 'pdf', 'eps', 'ai', 'cdr', 'wmf', 'eme'))]),
        ),
    ]
