# Generated by Django 5.0.2 on 2024-05-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='close_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='media_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='open_question',
            field=models.BooleanField(default=False),
        ),
    ]
