# Generated by Django 5.0.2 on 2024-02-26 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_question_time_to_answer_alter_question_image_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_after',
            field=models.FileField(blank=True, null=True, upload_to='media_after_question/image/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'jpeg200', 'gif', 'tiff', 'bmp', 'webp', 'psd', 'heif', 'svg', 'pdf', 'eps', 'ai', 'cdr', 'wmf', 'eme'))]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_before',
            field=models.FileField(blank=True, null=True, upload_to='media_before_question/image/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'jpeg200', 'gif', 'tiff', 'bmp', 'webp', 'psd', 'heif', 'svg', 'pdf', 'eps', 'ai', 'cdr', 'wmf', 'eme'))]),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_after',
            field=models.FileField(blank=True, null=True, upload_to='media_after_question/video', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'jpeg200', 'gif', 'tiff', 'bmp', 'webp', 'psd', 'heif', 'svg', 'pdf', 'eps', 'ai', 'cdr', 'wmf', 'eme'))]),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_before',
            field=models.FileField(blank=True, null=True, upload_to='media_before_question/video', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'jpeg200', 'gif', 'tiff', 'bmp', 'webp', 'psd', 'heif', 'svg', 'pdf', 'eps', 'ai', 'cdr', 'wmf', 'eme'))]),
        ),
    ]
