# Generated by Django 5.0.2 on 2024-06-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_question_close_question_question_media_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
