# Generated by Django 5.0.2 on 2024-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_question_image_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='image_after',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_before',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_after',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_before',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
