# Generated by Django 5.0.2 on 2024-03-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_alter_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='player_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
