# Generated by Django 5.0.2 on 2024-07-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_alter_question_image_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_after',
            field=models.ImageField(default=None, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_before',
            field=models.ImageField(default=None, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_after',
            field=models.FileField(default=None, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_before',
            field=models.FileField(default=None, null=True, upload_to='media/'),
        ),
    ]
