# Generated by Django 5.0.2 on 2024-03-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_mediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
