# Generated by Django 5.0.3 on 2024-03-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_question_answer_alter_question_time_to_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
