# Generated by Django 5.0.2 on 2024-03-21 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_alter_question_answers_alter_question_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='round_id',
        ),
        migrations.AddField(
            model_name='question',
            name='round_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='generator.round'),
        ),
    ]
