# Generated by Django 5.0.2 on 2024-03-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_alter_question_answers_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='blitz_score',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
