# Generated by Django 5.0.2 on 2024-03-21 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_remove_question_round_id_question_round_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='round_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generator.round'),
        ),
    ]
